source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

use_frameworks!

target 'ZSNetServe_Example' do
  pod 'ZSNetServe', :path => '../'

  target 'ZSNetServe_Tests' do
    inherit! :search_paths

    
  end
end
